/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cablebillinggui;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author autocad
 */
public class CableBillingGUIForm extends javax.swing.JFrame {

    /**
     * Creates new form CableBillingGUIForm
     */
    
    // static variable commercial customer
    static final double COM_PROCESS_FEE = 15;
    static final double COM_SERVICE_FEE = 75;
    static final double COM_CONNECTION_FEE = 5;
    static final double COM_HD_CHANNEL = 50;

    // static variable residential user
    static final double RES_PROCESS_FEE = 25;
    static final double RES_SERVICE_FEE = 105;
    static final double RES_CONNECT_FEE = 25;
    static final double RES_HD_CHANNEL = 150;
        
    String AcctType1 = "Residential";
    String AcctType2 = "Commercial";
    String AcctF = "Residential";
    String BillUpdated1 = "Yes";
    String BillUpdated2 = "No";
    String BillUpdatedF = "Yes";
    String BillVerified1 = "e-mail";
    String BillVerified2 = "fax";
    String BillVerified3 = "phone";
    String BillVerifiedF = "e-mail";
    String HistDeli1= "Yes";
    String HistDeli2= "No";
    String HistDeliF= "Yes";
    Double ComA, ComB, ComC, aComHD, DisaComHD, totalDisaComHD, aResHD, ResA, ResB, ResC;
    
    public CableBillingGUIForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtActNum = new javax.swing.JTextField();
        txtCusName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtYears = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHDChan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtActNumF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCusNameF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtYearsF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtHDChanF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtProcess = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBasicFee = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtConFee = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtChanFee = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtBillVeri = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTotalCharge = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Day 3");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CableBillingGUI"));

        jLabel1.setText(" Customer Name:");

        jLabel2.setText("Account Number:");

        jLabel3.setText("Account Type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Residential", "Commercial" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Years of subscription:");

        jLabel5.setText("Number of HD Channels ordered (Minimum of 2):");

        jLabel6.setText("Bills up to date?:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Bill verified through: ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "e-mail", "fax", "phone" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton1.setText("PROCESS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("History of delinquency?:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtHDChan)
                .addGap(102, 102, 102))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtYears, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtActNum, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtActNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHDChan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Account Number :");

        jLabel12.setText("Customer Name :");

        jLabel10.setText("Years Subscribed : ");

        jLabel11.setText("HD Channels ordered: ");

        jLabel13.setText("Processing Fee: Php");

        jLabel14.setText("Basic Service Fee: Php");

        jLabel15.setText("Basic Connection Fee: Php");

        jLabel16.setText("HD Channels Fee: Php");

        jLabel17.setText("Bill verified through: ");

        jLabel18.setText("Total Charge: Php");

        jLabel19.setText("Remarks: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYearsF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProcess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBillVeri, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtConFee, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotalCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtChanFee, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtHDChanF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBasicFee, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCusNameF))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActNumF))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtRemarks)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtActNumF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCusNameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtYearsF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtHDChanF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtBasicFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtConFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtChanFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtBillVeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtTotalCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-474)/2, (screenSize.height-653)/2, 474, 653);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        compute();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
      JComboBox cb = (JComboBox)evt.getSource();
      String newSelection1 = (String)cb.getSelectedItem();
      
      if (newSelection1.contentEquals(AcctType1)){
          AcctF = AcctType1;
      }else{
          AcctF = AcctType2;
      }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
      JComboBox cb2 = (JComboBox)evt.getSource();
      String newSelection2 = (String)cb2.getSelectedItem();
      
      if (newSelection2.contentEquals(BillUpdated1)){
          BillUpdatedF = BillUpdated1;
      }else{
          BillUpdatedF = BillUpdated2;
      }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        
      JComboBox cb3 = (JComboBox)evt.getSource();
      String newSelection3 = (String)cb3.getSelectedItem();
      
      if (newSelection3.contentEquals(BillVerified1)){
          BillVerifiedF = BillVerified1;
      }else if (newSelection3.contentEquals(BillVerified2)){
          BillVerifiedF = BillVerified2;
      }else{
          BillVerifiedF = BillVerified3;
      }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        
      JComboBox cb4 = (JComboBox)evt.getSource();
      String newSelection4 = (String)cb4.getSelectedItem();
      
      if (newSelection4.contentEquals(HistDeli1)){
         HistDeliF = HistDeli1;
      }else{
         HistDeliF = HistDeli2;
      }
        
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void compute() {
       
        String AcctNum = txtActNum.getText();
        String CustName = txtCusName.getText();
        Integer YearSub = Integer.parseInt (txtYears.getText());
        Integer hdChan = Integer.parseInt(txtHDChan.getText());
        
        if (hdChan < 2){
            JOptionPane.showMessageDialog(null, "Minimum entry for HD Channels is 2" + "\n" + "Please input a valid number.");
            
        }else{
            if (AcctF == "Commercial" && YearSub >= 2 && BillUpdatedF == "Yes"){
                aComHD = hdChan * COM_HD_CHANNEL;
                DisaComHD = aComHD * .10;
                Double totalDisaComHD = aComHD - DisaComHD;
                Double ComA = COM_SERVICE_FEE + COM_CONNECTION_FEE + totalDisaComHD;
                
                txtActNumF.setText(AcctNum);
                txtCusNameF.setText(CustName);
                txtYearsF.setText(YearSub.toString());
                txtHDChanF.setText(hdChan.toString());
                txtProcess.setText("Waived");
                txtBasicFee.setText("75.00");
                txtConFee.setText("5.00");
                txtChanFee.setText(String.format("%.2f",totalDisaComHD).toString());
                txtBillVeri.setText(BillVerifiedF);
                txtTotalCharge.setText(String.format("%.2f",ComA).toString());
                txtRemarks.setText("2 or more years of subscription / updated bill / 10% discount");
                
            }else if (AcctF == "Commercial" && YearSub < 2 && BillUpdatedF == "Yes" && HistDeliF == "Yes"){
               
                aComHD = hdChan * COM_HD_CHANNEL;
                ComC = COM_PROCESS_FEE + COM_SERVICE_FEE + COM_CONNECTION_FEE + aComHD;
                
                txtActNumF.setText(AcctNum);
                txtCusNameF.setText(CustName);
                txtYearsF.setText(YearSub.toString());
                txtHDChanF.setText(hdChan.toString());
                txtProcess.setText("15.00");
                txtBasicFee.setText("75.00");
                txtConFee.setText("5.00");
                txtChanFee.setText(String.format("%.2f",aComHD).toString());
                txtBillVeri.setText(BillVerifiedF);
                txtTotalCharge.setText(String.format("%.2f",ComC).toString());
                txtRemarks.setText("Less than 2 years subscription / delinquent updated bill / no 10% discount");

            }else if (AcctF == "Commercial" && YearSub < 2 && BillUpdatedF == "Yes" && HistDeliF == "No"){
                
                aComHD = hdChan * COM_HD_CHANNEL;
                DisaComHD = aComHD * .10;
                totalDisaComHD = aComHD - DisaComHD;
                ComB = COM_SERVICE_FEE + COM_CONNECTION_FEE + totalDisaComHD;
                
                txtActNumF.setText(AcctNum);
                txtCusNameF.setText(CustName);
                txtYearsF.setText(YearSub.toString());
                txtHDChanF.setText(hdChan.toString());
                txtProcess.setText("Waived");
                txtBasicFee.setText("75.00");
                txtConFee.setText("5.00");
                txtChanFee.setText(String.format("%.2f",totalDisaComHD).toString());
                txtBillVeri.setText(BillVerifiedF);
                txtTotalCharge.setText(String.format("%.2f",ComB).toString());
                txtRemarks.setText("Less than 2 years subscription / not delinquent / updated bill / 10% Discount");
                
            }else if (AcctF == "Residential" && YearSub >= 5){
                
                aResHD = hdChan * RES_HD_CHANNEL;
		ResA = RES_SERVICE_FEE + RES_CONNECT_FEE + aResHD;
                
                txtActNumF.setText(AcctNum);
                txtCusNameF.setText(CustName);
                txtYearsF.setText(YearSub.toString());
                txtHDChanF.setText(hdChan.toString());
                txtProcess.setText("Waived");
                txtBasicFee.setText("105.00");
                txtConFee.setText("25.00");
                txtChanFee.setText(String.format("%.2f",aResHD).toString());
                txtBillVeri.setText(BillVerifiedF);
                txtTotalCharge.setText(String.format("%.2f",ResA).toString());
                txtRemarks.setText("5 or more years of subscription / updated bill");
                
            }else if(AcctF == "Residential" && YearSub == 2 || YearSub == 3 || YearSub == 4 && HistDeliF == "Yes"){
                
                aResHD = hdChan * RES_HD_CHANNEL;
		ResB = RES_PROCESS_FEE + RES_SERVICE_FEE + RES_CONNECT_FEE + aResHD;
                
                txtActNumF.setText(AcctNum);
                txtCusNameF.setText(CustName);
                txtYearsF.setText(YearSub.toString());
                txtHDChanF.setText(hdChan.toString());
                txtProcess.setText("25.00");
                txtBasicFee.setText("105.00");
                txtConFee.setText("25.00");
                txtChanFee.setText(String.format("%.2f",aResHD).toString());
                txtBillVeri.setText(BillVerifiedF);
                txtTotalCharge.setText(String.format("%.2f",ResB).toString());
                txtRemarks.setText("2 to 4 years of subscription / updated bill / delinquent");
            
            }else if(AcctF == "Residential" && YearSub == 2 || YearSub == 3 || YearSub == 4 && HistDeliF == "No"){
                
                aResHD = hdChan * RES_HD_CHANNEL;
		ResB = RES_PROCESS_FEE + RES_SERVICE_FEE + RES_CONNECT_FEE + aResHD;
                
                txtActNumF.setText(AcctNum);
                txtCusNameF.setText(CustName);
                txtYearsF.setText(YearSub.toString());
                txtHDChanF.setText(hdChan.toString());
                txtProcess.setText("Waived");
                txtBasicFee.setText("105.00");
                txtConFee.setText("25.00");
                txtChanFee.setText(String.format("%.2f",aResHD).toString());
                txtBillVeri.setText(BillVerifiedF);
                txtTotalCharge.setText(String.format("%.2f",ResB).toString());
                txtRemarks.setText("2 to 4 years of subscription / updated bill / not delinquent");
                
            }else {
                
                aResHD = hdChan * RES_HD_CHANNEL;
		ResC = RES_PROCESS_FEE + RES_SERVICE_FEE + RES_CONNECT_FEE + aResHD;
                
                txtActNumF.setText(AcctNum);
                txtCusNameF.setText(CustName);
                txtYearsF.setText(YearSub.toString());
                txtHDChanF.setText(hdChan.toString());
                txtProcess.setText("25.00");
                txtBasicFee.setText("105.00");
                txtConFee.setText("25.00");
                txtChanFee.setText(String.format("%.2f",aResHD).toString());
                txtBillVeri.setText(BillVerifiedF);
                txtTotalCharge.setText(String.format("%.2f",ResC).toString());
                txtRemarks.setText("1 year or less subscription / updated bill");
                
            }
            
            
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CableBillingGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CableBillingGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CableBillingGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CableBillingGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CableBillingGUIForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtActNum;
    private javax.swing.JTextField txtActNumF;
    private javax.swing.JTextField txtBasicFee;
    private javax.swing.JTextField txtBillVeri;
    private javax.swing.JTextField txtChanFee;
    private javax.swing.JTextField txtConFee;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtCusNameF;
    private javax.swing.JTextField txtHDChan;
    private javax.swing.JTextField txtHDChanF;
    private javax.swing.JTextField txtProcess;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtTotalCharge;
    private javax.swing.JTextField txtYears;
    private javax.swing.JTextField txtYearsF;
    // End of variables declaration//GEN-END:variables
}
