/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Payroll1GUI;

import guiall.GUIALLFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author autocad
 */
public class Payroll1GUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form Payroll1GUIFrame
     */
    public Payroll1GUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        dept = new javax.swing.JTextField();
        absent = new javax.swing.JTextField();
        go = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Day 1");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Payroll1GUI"));

        jLabel1.setText("Enter Name:");

        jLabel2.setText("Enter Department:");

        jLabel3.setText("Enter Days Absent:");

        go.setText("Compute");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        go.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                goKeyPressed(evt);
            }
        });

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(go))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(absent, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(dept, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(absent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(go)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-276)/2, (screenSize.height-256)/2, 276, 256);
    }// </editor-fold>//GEN-END:initComponents

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        calculate();
        
    }//GEN-LAST:event_goActionPerformed
    private void calculate() {
        String nme = (String) (this.name.getText()); 
        String dept = (String) (this.dept.getText());
        Integer abs = Integer.parseInt(absent.getText());
        
	int hour;
	double day, week, month, wage, sss, pbg, tax, ttax, phl, twage, tabs;
        
        hour = 300;
	day = hour * 8;
        week = day * 5;
        month = week * 4;
        tabs = abs*day;
        wage = month - (abs*day);
        
        sss = month * .10;
        pbg = month * .10;
        tax = ((20-abs) * day);
	ttax = tax * .20;
        phl = month * .10;
        twage = wage - (pbg+sss+phl+ttax);
        
        if (abs > 0){
            JOptionPane.showMessageDialog(null,"Employee Details:" + "\n" + "\n" + "Name : " + nme + "\n" + "Department : " + dept + "\n" + "\n" + 
                                            "Salary Details:" + "\n" + "\n" +"Your Hourly Rate is : Php 300.00" + "\n" + "Your Daily Rate is : Php " + String.format("%.2f", day) +
                                            "\n" + "Your Weekly Rate is : Php " + String.format("%.2f", week) + "\n" + "Your Monthly Rate is : Php " + String.format("%.2f", month) +
                                             "\n" + "\n" + "Deductions:" + "\n" + "\n" +  "SSS : Php " + String.format("%.2f", sss ) + "\n" + "Pag-Ibig : Php " + String.format("%.2f", pbg) + "\n" + "Witholding Tax less " + abs + " absence/s : Php " + String.format("%.2f", ttax) +
                                             "\n" + "PhilHealth : Php " + String.format("%.2f", phl) + "\n" + "\n" + "Salary Computation:" + "\n" + "\n" + "Your Total Workday/s in a Month : " + (20-abs) + " days " +"\n" + "Deduction from " + abs + " absence/s : Php " +  String.format("%.2f", tabs) +
                                             "\n" + "Your Total Basic Income : Php " + String.format("%.2f", wage) + "\n" + "Less Monthly Deductions : Php " + String.format("%.2f", (pbg+sss+phl+ttax)) + "\n" + "Your Total Wage with Absence/s : Php " + String.format("%.2f", twage) );
        
            
        }else{
            JOptionPane.showMessageDialog(null,"Employee Details:" + "\n" + "\n" + "Name : " + nme + "\n" + "Department : " + dept + "\n" + "\n" + 
                                            "Salary Details:" + "\n" + "\n" +"Your Hourly Rate is : Php 300.00" + "\n" + "Your Daily Rate is : Php " + String.format("%.2f", day) +
                                            "\n" + "Your Weekly Rate is : Php " + String.format("%.2f", week) + "\n" + "Your Monthly Rate is : Php " + String.format("%.2f", month) +
                                             "\n" + "\n" + "Deductions:" + "\n" + "\n" +  "SSS : Php " + String.format("%.2f", sss ) + "\n" + "Pag-Ibig : Php " + String.format("%.2f", pbg) + "\n" + "Witholding Tax : Php " + String.format("%.2f", ttax) +
                                             "\n" + "PhilHealth : Php " + String.format("%.2f", phl) + "\n" + "\n" + "Salary Computation:" + "\n" + "\n" + "Your Total Workday/s in a Month : " + (20-abs) + " days " + 
                                             "\n" + "Your Total Basic Income : Php " + String.format("%.2f", wage) + "\n" + "Less Monthly Deductions : Php " + String.format("%.2f", (pbg+sss+phl+ttax)) + "\n" + "Your Total Wage : Php " + String.format("%.2f", twage) );
        
        }
        name.setText("");
        this.dept.setText("");
        absent.setText("");
    }
    
    private void goKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_goKeyPressed
        calculate();
    }//GEN-LAST:event_goKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new GUIALLFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payroll1GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payroll1GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payroll1GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payroll1GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payroll1GUIFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absent;
    private javax.swing.JTextField dept;
    private javax.swing.JButton go;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
